SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS banned_url_patterns (
  id int(11) NOT NULL AUTO_INCREMENT,
  pattern varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  PRIMARY KEY (id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=224 ;

CREATE TABLE IF NOT EXISTS commands (
  id int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  lowercase_name varchar(255) COLLATE utf8_bin NOT NULL,
  url text COLLATE utf8_bin NOT NULL,
  description text COLLATE utf8_bin NOT NULL,
  uses int(11) NOT NULL DEFAULT '0',
  spam tinyint(4) NOT NULL DEFAULT '0',
  creation_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  last_use_date datetime DEFAULT '0000-00-00 00:00:00',
  golden_egg_date datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY `name` (`name`),
  KEY lowercase_name (lowercase_name)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=45202 ;

CREATE TABLE IF NOT EXISTS sessions (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  sessid varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `data` text COLLATE utf8_bin,
  PRIMARY KEY (id),
  KEY sessid (sessid)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
